# action.yml
name: 'nwmqpa/rust-musl-builder'
description: 'Build a rust binary using musl and cargo'
inputs:
  gh_user:
    description: 'The github user used for private repos'
    required: false
  gh_pat:
    description: 'The github private access token used for private repos'
    required: false
  command:
    description: 'The command to use inside the container'
    required: true
  sccache_bucket:
    description: 'The bucket used to store compilation artifacts'
    required: false
  aws_access_key_id:
    description: 'AWS Access key ID'
    required: false
  aws_secret_access_key:
    description: 'AWS Secret access key'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.gh_user }}
    - ${{ inputs.gh_pat }}
    - ${{ inputs.sccache_bucket }}
    - ${{ inputs.aws_access_key_id }}
    - ${{ inputs.aws_secret_access_key }}
